# Generated by Django 5.2.9 on 2026-04-27 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_2023", models.FileField(upload_to="uploads/")),
                ("uploaded_2025", models.FileField(upload_to="uploads/")),
                ("result_png", models.FileField(upload_to="images_upload/")),
                ("result_tif", models.FileField(upload_to="images_upload/")),
                ("result_shp", models.FileField(upload_to="images_upload/")),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpatialJoinResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_shapefile", models.FileField(upload_to="shapefiles/")),
                ("change_shapefile", models.FileField(upload_to="shapefiles/")),
                ("result_shapefile", models.FileField(upload_to="output/")),
                ("result_excel", models.FileField(upload_to="output/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
